### ISSUE TITLE
r4300.zip is corrupt

### ISSUE THREAD

**Issue by DerekTurtleRoe** [franckverrot/EmulationResources#1]
The r4300.zip file is corrupt, or at least I can't open it with anything I have (7-Zip, PeaZip, WinRAR, etc.).

This also applies to the @Emu-Docs copy on his repository. Not sure what is in this (presumably more datasheets or something) but I'm curious, so I want to know at least where you guys got this.

Hope this helps.

**Comment by franckverrot** [comment]
Ahah awesome... So it's basically my fault from when I collected those docs back in 2000-something for (the now dead)dev-fr.com(http://dev-fr.com), and theirs for copying my repo.

Thanks for letting me know, I probably have a backup in my... parents basement (not kidding 😅) in France. I'll give it a look when I'll get back home.

Cheers!

Franck

## 

Franck Verrot
https://github.com/franckverrot
https://twitter.com/franckverrot

**Comment by DerekTurtleRoe** [comment]
@franckverrot Do you remember what is in the zip file? I may have a copy of whatever it is. I mean, I have pretty much everything else N64-related. :laughing:

**Comment by franckverrot** [comment]
Uploaded the file. I think it's this one and I got it directly from the official website :sweat_smile:

**Comment by DerekTurtleRoe** [comment]
@franckverrot Thanks! I did already have this file, but it is good we fixed the one in the repository. :wink:

**Comment by franckverrot** [comment]
Thanks for reporting it. Glad this repo can be useful.

On Fri, Feb 26, 2016 at 2:09 PM, vgturtle127 notifications@github.com
wrote:

> @franckverrot https://github.com/franckverrot Thanks! I did already
> have this file, but it is good we fixed the one in the repository. [image:
> :wink:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/franckverrot/EmulationResources/issues/1#issuecomment-189504290
> .

## 

Franck Verrot
https://github.com/franckverrot
https://twitter.com/franckverrot
